[package]
name = "stylesheet"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.3"
regex = "1"
lazy_static = "1.2.0"
thiserror = "1.0"
erased-serde = "0.3.25"
serde_json = "1.0.96"

[dependencies.serde]
version = "1.0.163"
features = ["derive"]
