[package]
name = "vg-rs"
version = "0.1.0"
edition = "2021"

[dependencies.geo-nd]
version = "0.5"

[dependencies.bezier-nd]
version = "0.5"

[dependencies.thiserror]
version = "1.0"

[dependencies.indent-display]
version = "0.1"
